### PR TITLE
pvh: Support booting via PVH ELFNOTE

### LINKED ISSUE #6: Support more VMMs (QEMU, crosvm, XEN)
Right now it's not possible to run the firmware with any non-Firecracker VMM. Ideally we would support a wide range of VMMs. There are many small changes that would fix this:

- [ ] In the ELF binary, advertise support for a common boot specification. This would allow any VMM supporting that spec to run the firmware. Our options are:
  - [Mutliboot/Multiboot2](https://en.wikipedia.org/wiki/Multiboot_specification): this is an older FSF common boot standard. It would also let us work with QEMU's `-kernel` option (might also work with Xen). 
  - [PVH direct boot](https://xenbits.xen.org/docs/unstable/misc/pvh.html): This standard [started with XEN](https://wiki.xen.org/wiki/Xen_Project_Software_Overview#PVH), but support was [added to QEMU](https://patchwork.kernel.org/cover/10715001/) recently. To use this, we just need to advertise `XEN_ELFNOTE_PHYS32_ENTRY` as an [ELFNOTE](https://elixir.bootlin.com/linux/latest/source/include/linux/elfnote.h). Not supporting PVH is why running QEMU with `-kernel` does not work:
    ```
    > qemu-system-x86_64 -kernel target/target/release/hypervisor-fw   
    qemu-system-x86_64: Error loading uncompressed kernel without PVH ELF Note
    ```
  - Note that both of these specs would (probably) require a separate 32-bit entry point. The firmware would then need to setup paging before jumping to the normal 64-bit ELF entry point (i.e. `_start`).

- [ ] Issue #5: support building the firmware as a flat BIOS binary (like `OVMF.fd`), allowing it to be directly loaded/executed by any VMM that supports SeaBIOS/OVMF.

Implementing either of these would let the firmware work on QEMU. I'm not sure about how to get it working for crosvm (it should "just work" with any ELF binary). I can ask around at work Monday to see what the deal is.

### PR DESCRIPTION
**Pull request by josephlr**
Fixes #6 

This PR adds support for booting via the [Xen HVM direct boot ABI](https://xenbits.xen.org/docs/4.12-testing/misc/pvh.html) otherwise known as the PVH Boot Protocol.

This required significant cleanup to how we load the Linux Kernel, as the existing code wasn't doing the exact correct thing. All of the commits that _don't_ start with `pvh:` are part of this cleanup. The commits that _do_ start with `pvh:` specifically address adding PVH support (including the transition for 32-bit to 64-bit mode).

This allows our firmware to be used with QEMU's `-kernel` option. This can be invoked like:
```
qemu-system-x86_64
-machine type=q35,accel=kvm \
-cpu host \
-smp 1 \
-m 1024 \
-display none \
-serial stdio \
-kernel target/target/release/hypervisor-fw \
-drive file=clear-28660-kvm.img,format=raw,if=none,id=boot-drive \
-device virtio-blk-pci,drive=boot-drive,disable-legacy=on
```

Also, as `cloud-hypervisor` supports loading PVH ELF binaries, the PVH entry point will also be used when using `cloud-hypervisor`'s `--kernel` option. This also means that no current hypervisors will use the Linux Boot Protocol path.

Signed-off-by: Joe Richey <joerichey@google.com>

### CODE REVIEW

**Comment by rbradford** [comment]
> @rbradford, is this the same issue that prevents booting on firecracker? Resetting Virtio Devices?

That manifests itself as a failure to mount the filesystem.  You would see a lot of kernel messages up to that point.

I think I know why it gets further: when using the -kernel entry point it will use Seabios with the PVH option ROM so it will go through that initialisation code (I also tried qboot and that still has a zero bar for the PCI device.)

Now that you're getting this far with I think you can probably use qemu's gdbserver with the kernel binary to check progress. 

Alternatively when I was developing this I build my own kernel and dropped it into the appropriate directory and used "outb" debugging to trace the progress though the assembly code. It might sound fiddly but if you script the build/mount image/copy binary/unmount then it isn't so bad.

**Comment by josephlr** [comment]
Good news, I've got some local changes that got the firmware all the way booting on QEMU.

Working on breaking them out into a reasonable patchset.

**Comment by josephlr** [comment]
@rbradford this code should now work with QEMU using the command in the PR description. Try it out and let me know if it works for you. I think it will be _much_ easier to merge this first and then work on #24 (where we need to deal with real-mode code and other subtleties).

This isn't quite ready, I still need to split this up (I ended up rewriting most of `src/bzimage.rs`). Note that the QEMU PVH implemenation has some minor bugs (I submitted [this patch](https://lists.gnu.org/archive/html/qemu-devel/2020-03/msg00560.html) to fix one), but none severe enough to keep Linux from booting.

**Comment by rbradford** [comment]
Very cool, works for me :+1:

**Comment by rbradford** [comment]
I had just a brief skim through the code changes and they look good. I look forward to seeing the breakdown into the individual commits.

**Comment by rbradford** [comment]
@josephlr How's this going? We now have PVH support in Cloud Hypervisor so looking forward to seeing this mature. :-)

**Comment by josephlr** [comment]
> @josephlr How's this going? We now have PVH support in Cloud Hypervisor so looking forward to seeing this mature. :-)

PTAL, this is now ready for review. I rewrote the commit history to explain all of the changes that are going on here. I had to rewrite most of `bzimage.rs` as we are now using a very different process to load the kernel.

Let me know if anything is unclear here. I'd be happy to reword any commit messages.

**Comment by josephlr** [comment]
> Looks good. I just want to run it through the integration tests for Cloud Hypervisor.

@rbradford I just added https://github.com/cloud-hypervisor/rust-hypervisor-firmware/pull/26/commits/4fd16771579ec1e2322869b2c52c0bf3aee71249 (which removes the serial debugging in the ASM) and https://github.com/cloud-hypervisor/rust-hypervisor-firmware/pull/26/commits/6ef27a140ef63f2268c3c53925c419469fe86f3c (which cleans up and comments the linker script).

I just wanted to make sure those commits didn't get missed.

File: src/fat.rs [hunk 1]
```diff
@@ -244,6 +244,24 @@ pub trait Read {
     fn read(&mut self, data: &mut [u8]) -> Result<u32, Error>;
     fn seek(&mut self, offset: u32) -> Result<(), Error>;
     fn get_size(&self) -> u32;
+
+    // Loads the remainer of the file into the specified memory region
```
Comment (josephlr) [inline src/fat.rs]: Typo: Remainder

**Comment by rbradford** [comment]
@josephlr cool to merge this if you're ready?

**Comment by josephlr** [comment]
> @josephlr cool to merge this if you're ready?

@rbradford SGTM
